### ISSUE TITLE
Component missing/your thoughts?

### ISSUE THREAD

**Issue by elgerlambert** [zippyui/react-checkbox#1]
Hi radubrehar,

How's it going? I was about to create a generic checkbox component and then came looking on github to see if anyone had already done so. When I saw your name I came to have a look. Unfortunately it doesn't look like the repo actually contains a component.

My use-case is as follows. I'd like to be able to define what the truth and false values of the checkbox are, similar to checkboxes in angular I suppose: https://docs.angularjs.org/api/ng/input/input%5Bcheckbox%5D

Does this coincide with what you had in mind/have worked on? It's a simple enough component, just figured if somebody had already created one I'd rather use that. Alternative is, I create a repo myself.

**Comment by radubrehar** [comment]
Hi Elger!

I have just published the checkbox. You can now find in the README the supported features.
My thought was to implement support for the indeterminate state (under the `supportIndeterminate` prop flag), with the option for a custom value specified for this state.
I don't see good reasons trying to specify `checked` something different than `true`/`false` - if you do need this, just do `<Checkbox checked={value===customCheckedValue} />` - other than supporting the indeterminate state (useful in trees of data)

So this component is meant to be a very thin wrapper around `<input type="checkbox" />`, with additional support for indeterminate state.

What I do find useful sometimes is to be able to submit different values for checked/unchecked/indeterminate states. For this, see [react-check3](https://github.com/radubrehar/react-check3), which is a custom checkbox - navigatable, looking the same on all browsers, etc.

What are your thoughts?
