### ISSUE TITLE
Doesn't work for latest react

### ISSUE THREAD

**Issue by lbargery** [zippyui/react-checkbox#5]
Hey,

I am using this as a simple tri-state checkbox but I am using react 15.0.2. I've upgraded the class myself and to use React 15.0.2 and use the latest version of javascript (ES6) (I'm using babel). Happy to share my code with you? I don't have time right now to fiddle with the webpack settings so that it can be used as an npm module but should just be a case of including babel really.

Thanks for the original code :)

Laurence

**Comment by bogdanpetru** [comment]
The codebase has been updated to work with react 15.
